<a href="https://colab.research.google.com/github/jlillie2022/Data-Science/blob/main/Jenna_Lillie_Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Loops

In [ ]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
for i in range(5,8):
    print(i)

5
6
7


In [ ]:
  for i in range(3):
      print("Test Number:  ",i)

Test Number:   0
Test Number:   1
Test Number:   2


#functions

In [ ]:
  def square(x):
      return x**2
    

In [ ]:
square (5)

25

In [ ]:
square (221)

48841

In [ ]:
square(square(5))

625

In [ ]:
def add_two(x):
    return x+2

In [ ]:
add_two(5)

7

In [ ]:
square(add_two(5))

49

In [ ]:
choice="apple"

In [ ]:
if choice == "apple":

  print("you choose apples.")
  
else:

  print("you did not choose apples.")

you choose apples.


In [ ]:
if choice == "apple":

    print("you choose apples.")
    print("thank you,shop again!")

elif choice == "orange":

    print("you choose oranges")
    print("thank you,shop again!")

else:

    print("you did not choose apples or oranges.")
    print("thank you,shop again!")

you choose apples.
thank you,shop again!


#user input

In [ ]:
choice = input("Please enter your choice (i.e. apple): ")


Please enter your choice (i.e. apple): oranges


In [ ]:
choice

'oranges'

In [ ]:
import numpy as np

In [ ]:
np.random.permutation(52)

array([21,  5, 35,  4, 24, 19, 37,  3, 20, 26, 38, 34, 15, 40, 11, 42,  6,
       12, 51, 17, 28, 10,  2, 29, 48,  0, 32, 41,  7, 16, 44,  1, 47, 43,
        9, 33, 13, 45, 31, 14, 22, 23,  8, 39, 30, 25, 50, 27, 18, 49, 46,
       36])

In [ ]:
cards = np.random.permutation(52)

In [ ]:
cards[0]

18

In [ ]:
cards[1]

40

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

In [ ]:
  np.arange(52).reshape(4,13)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [ ]:
  np.arange(52).reshape(4,13)%13

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [ ]:
  np.arange(52).reshape(4,13)//13

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [ ]:
suits=['clubs','spades','hearts','diamonds']
names=['ace','two','three','four','five','six','seven','eight','nine','ten','jack','queen','king']

In [ ]:
def card_name(card_number):
    
    suit = card_number//13
    name = card_number%13

    return names[name] + " of " + suits[suit]

In [ ]:
cards = np.random.permutation(52)

In [ ]:
  top_of_deck         = card_name(cards[0])
  second_card_in_deck = card_name(cards[1])
  last_card_in_deck   = card_name(cards[-1])

In [ ]:
top_of_deck,second_card_in_deck,last_card_in_deck

('two of diamonds', 'six of diamonds', 'five of spades')

In [ ]:
card_url_head="https://www.improvemagic.com/wp-content/uploads/2020/11/"
card_url_tail=".png"

In [ ]:
suit=['k','p','s','1']
card=['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King']

In [ ]:
i=np.random.randint(4)
j=np.random.randint(13)

In [ ]:
i,j

(2, 2)

In [ ]:
suit[i]

's'

In [ ]:
card[j]

'Three'

In [ ]:
from IPython.core.display import display, HTML

In [ ]:
def show_img(img):
    display(HTML('<img src='+img+'>'))

In [ ]:
img=card_url_head+suit[i]+card[j]+card_url_tail

In [ ]:
show_img(img)